# Generated by Django 3.0.6 on 2020-05-29 19:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("link", models.SlugField(max_length=260, unique=True)),
                (
                    "creating_date",
                    models.DateTimeField(
                        default=datetime.date.today, verbose_name="Creating date"
                    ),
                ),
                (
                    "vote",
                    models.SmallIntegerField(
                        default=0,
                        help_text="to vote the post",
                        verbose_name="Amount of votes",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Post", "verbose_name_plural": "Posts",},
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=150, verbose_name="Author name"),
                ),
                ("content", models.TextField(max_length=500, verbose_name="Content")),
                (
                    "creating_date",
                    models.DateTimeField(
                        default=datetime.date.today, verbose_name="Creating date"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="news_api.Post",
                        verbose_name="post",
                    ),
                ),
            ],
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments",},
        ),
    ]
