# Generated by Django 3.0.6 on 2020-05-30 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-creating_date"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-vote"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_name",
            field=models.CharField(max_length=150, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="creating_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Creating date"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="news_api.Post",
                verbose_name="post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(default=1, max_length=150, verbose_name="Author"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="creating_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Creating date"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="link",
            field=models.SlugField(max_length=260, unique=True, verbose_name="Link"),
        ),
        migrations.AlterUniqueTogether(
            name="post", unique_together={("title", "link")},
        ),
    ]
