version: '3.7'

services:
  django:
    build: .
    command: gunicorn news.wsgi:application --bind 0.0.0.0:8000
#    command: python manage.py migrate
#    volumes:
#      - ./:/app
    volumes:
      - static_volume:/app/staticfiles
#    ports:
#      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bohdan
      - POSTGRES_PASSWORD=bohdan
      - POSTGRES_DB=news
    ports:
      - 5432:5432
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - django
volumes:
  postgres_data:
  static_volume:
